export const COMPANYLOAD = "COMPANYLOAD";

export const ADDCOMPANYSUCC = "ADDCOMPANYSUCC";
export const ADDCOMPANYFAIL = "ADDCOMPANYFAIL";

export const GETCOMPANYSUCC = "GETCOMPANYSUCC";
export const GETCOMPANYFAIL = "GETCOMPANYFAIL";

export const EDITCOMPANYFAIL = "EDITCOMPANYFAIL";
export const EDITCOMPANYSUCC = "EDITCOMPANYSUCC";